swagger: "2.0"
info:
  description: "Backend REST API using Node, Express, Sequelize and MySql with Spotify API"
  version: "1.0.1"
  title: "🎹 Spotify Audio Track REST API 🎹"
  
servers:
  - url: https://heroku-mysql-demo-api.herokuapp.com
    description: Optional server description, e.g. Main (production) server
  - url: https://heroku-mysql-demo-api.herokuapp.com
    description: Optional server description, e.g. Internal staging server for testing

schemes: 
  - http
  - https

host: 
 # - heroku-mysql-demo-api.herokuapp.com
 # - localhost:7001

basePath: "/v1/api/isrc"

paths:
  